### ISSUE TITLE
LED-Typ oder -Name bei der Wetter-Profil-Zuweisung anzeigen

### ISSUE THREAD

**Issue by coolcow** [LEDaquaristik/sunriser#3]
Bei der Wetter-Profil-Zuweisung werden die LEDs nur mit `LED #1`, `LED #2` etc angezeigt...
...das ist nicht sehr praktisch, da man nicht immer weiß welche LED welche ist.

![auswahl_034](https://user-images.githubusercontent.com/2337234/31737939-641f5f40-b449-11e7-8449-11b24c7a6fef.png)

Hier wäre es ganz sinnvoll zusätzlich den LED-Typ mit anzuzeigen. In meinem Fall `TROPIC 4500K` z.B. =>
![auswahl_035](https://user-images.githubusercontent.com/2337234/31737951-70a2f22c-b449-11e7-9943-c1d87bfc6796.png)

Alternativ wäre es auch ganz sinnvoll die LEDs benennen zu können (`LED #1` => `vordere SUNSET` z.B.) und diese Bezeichnung dann anzuzeigen...

**Comment by jeanatcismet** [comment]
keiner zuhause ? schade...

**Comment by coolcow** [comment]
niemand zuhause ?! schade...
