### ISSUE TITLE
Gewitter geht nicht

### ISSUE THREAD

**Issue by silke21** [LEDaquaristik/sunriser#4]
Wahrscheinlichkeit eines Gewitters pro maximale Anzahl von Gewittern am Tag: | 100 |  
-- | -- | --
 
Maximale Anzahl von Gewittern pro Tag: 4 Gewitter nur wenn LED Tagesplanung auf 0 %        aus

**Comment by coolcow** [comment]
Kann ich so bestätigen, aber ich fürchte hier schaut der Entwickler nicht rein... Wozu auch, wer hier was postet hat ja schließlich schon längst bezahlt.

**Comment by Getty** [comment]
Wir schauen hier nicht rein, weil hier halt kein Support ist, und nicht für eigentliche Entwicklung Anfragen gesammelt werden. Auch ist es halt nicht 24/7 Gewitter mit diesem Setting, bitte einfach noch mal prüfen.

**Comment by coolcow** [comment]
Vielleicht dann einfach mal die issues deaktivieren, wenn man sage und schreibe 6 Jahre braucht um darauf zu antworten, dass man gar keine möchte... ?
Ich freue mich schon auf sie Antwort im Januar 2030.

**Comment by Getty** [comment]
Ich hatte sogar damals die Fehler gesehen hier und dann ehr damit reagiert weiter an der Software zu arbeiten, und dabei vergessen hier was nachzulegen. Hatten Sie das Problem auch damals beim Support gemeldet, weil dann hatten Sie ja Antwort bekommen.
