### ISSUE TITLE
fonts.css 

### ISSUE THREAD

**Issue by AdamPerkins** [LEDaquaristik/sunriser#8]
Die ganzen Fonts sind hardcoded auf http://srdemo.ledaquaristik.de verlinkt.

Das ist schlecht. Erstens ist es ein erstklassiger (verbotener) Tracker. Zweitens verlangsamt es den Seitenaufbau ein klein wenig und drittens belastet dies euren Server unötig.

Wie ein Test ergeben hat, sind die Fonts ja lokal auf dem Gerät vorhanden.

**Comment by Getty** [comment]
Eigentlich sind die verlinkt, weil es dann schneller geht, weil das arme Gerät die Daten nicht so schnell liefern kann wie das der Server aus dem Internet tut. Die Fonts sind vorhanden, laden aber langsamer. Wir nutzen ja auch, wenn Sie das vielleicht übersehen haben, die lokalen Dateien als Fallback wenn die Cloud nicht verfügbar ist.
