### ISSUE TITLE
sunriser startet ungewollt neu

### ISSUE THREAD

**Issue by findies** [LEDaquaristik/sunriser#9]
Assertion "tcp_connect: invalid ipaddr" failed at line 1078 in lwip/src/core/tcp.c

17.06.2022 18:22.51] !!! error on dns_gethostbyname on sr_finder_callhome: -1
[17.06.2022 18:24.51] !!! error on dns_gethostbyname on sr_finder_callhome: -1
[17.06.2022 18:26.51] !!! error on dns_gethostbyname on sr_finder_callhome: -1
[17.06.2022 18:26.53] Link Down
[17.06.2022 18:26.53] Interface Down
[17.06.2022 18:32.08] Link Down
[17.06.2022 18:32.08] Interface Down
[17.06.2022 19:20.33] Link Down
[17.06.2022 19:20.33] Interface Down
[17.06.2022 19:20.44] Link Down
[17.06.2022 19:20.44] Interface Down
[10.08.2022 11:40.52] Link Down
[10.08.2022 11:40.52] Interface Down
[10.08.2022 11:41.02] Link Down
[10.08.2022 11:41.02] Interface Down
[05.09.2022 16:17.23] !!! error on opening configdir <CFGBACK1> fr:5
[05.09.2022 16:17.23] !!! error on backup generation
[05.09.2022 16:17.26] !!! error on opening configdir <CFGBACK1> fr:5
[05.09.2022 16:17.26] !!! error on backup generation
[01.10.2022 17:20.32] !!! error on reading new service_value err:Invalid type
[01.10.2022 17:20.32] !!! error on reading new service_value err:Invalid type
[01.10.2022 17:20.32] !!! error on reading new service_value err:Invalid type
[01.10.2022 17:20.32] !!! error on reading new service_value err:Invalid type
[21.10.2022 12:19.08] Link Down
[21.10.2022 12:19.08] Interface Down
[21.10.2022 12:19.19] Link Down
[21.10.2022 12:19.19] Interface Down
[07.11.2022 19:25.52] !!! error on opening <FIRMWARE.BEE> fr:1

**Comment by findies** [comment]
Sorry für die verspätete Beschreibung, wollte gestern erstmal nur schnell das Fehler-Log sichern.
sunriser startet neu (Led's gehen aus und nach einiger zeit wieder an), wenn im Netzwerk auf alternativ Gerät zugegriffen wird.
Sunriser hängt an einem FritzRepaeter(1200) per Lan, der Repeater hängt per Mesh an der FritzBox.

Sobald man auf ein Gerät(hier ein shelly) zugreift, (meist per http), welches auch am WLAN des Repeaters hängt, startet der sunriser8 neu.

Der sunriser erhält sein IP per DHCP von der FritzBox, nicht fest vergeben.an der FritzBox jedoch eingestellt, das die MAC-Adresse des sunrisers immer dieselbe IP bekommen soll.

Ich weiß ehrlich gesagt nicht weiter, warum der sunriser dann ständig bootet.
Gruß
Torsten

**Comment by LarsK1** [comment]
Hi @findies,
hatte das gleiche Problem wie du. Ich konnte es lösen, indem ich die eingebaute SD-Karte ausgebaut habe und die neue Firmware installiert habe .
```
Lösung 2

Sollte oben erklärtes Vorgehen erfolglos bleiben, können Sie alternativ dazu den SunRiser 8 öffnen und die MicroSD-Karte entnehmen.

Siehe dazu ein Foto unter: http://srdemo.ledaquaristik.de/img/sdcard.jpg

Achtung, bevor Sie beginnen, ist die Stromversorgung zu trennen und sind alle Stecker der LEDs abzustecken.

Das Austauschen der MicroSD-Karte hat keinerlei Auswirkungen auf Garantie oder Gewährleistung, wir sehen dies als reguläre Benutzung des Geräts.

Nun formatieren Sie die MicroSD-Karte neu (FAT32, keine Schnellformatierung) und speichern anschließend die Firmware-Datei „NEW.BEE“ auf der neuformatierten Karte. (Es kann auch eine andere/neue SD-Karte beliebiger Größe (ab 2GB) verwendet werden.)

Download der aktuellesten SunRiser 8 Firmware („NEW.BEE“) unter: http://sunriser.ledaquaristik.de/NEW.BEE

Anschließend kann die Karte wieder in den SunRiser 8 einsetzen und das Gerät schließen. Die Firmware wird beim Einschalten automatisch installiert und der SunRiser startet neu. Nach dem Neustart können Sie Ihre persönliche Sicherungsdatei in gewohnter Weise einlesen.
```

**Comment by Getty** [comment]
Ja, dies sind alles normale Support Fälle und nicht für GitHub. Der Assertion Fehler ist sogar vollkommen irrelevant und kann halt manchmal passieren hat aber keine Auswirkungen, dier Basis Grund ist die defekte SD Karte wie schon erwähnt, ich verweise da auf:

https://srdemo.ledaquaristik.de/faq.html#sdbroken

Bitte hier keine Support Anfragen reinsetzen, dies hat nichts mit der Software vom SunRiser zutun.

**Comment by tvonall** [comment]
?
Um was geht es da?
Mit freundlichen Grüßen

**Comment by findies** [comment]
Es können ja nicht 3 SD Karten auf einmal defekt sein. Ich habe das LAN-Kabel gezogen, seitdem startet er nicht mehr neu.
Läuft jetzt halt offline.

**Comment by Getty** [comment]
Wir hatten bisher nur einen einzigen Kunden der einen TV Receiver hatte, der den SunRiser lahmgelegt hat, einfach weil dieser zu viele Pakete an den SunRiser schickte als dieser Verarbeiten konnte, der ist ja sehr schwach und antwortet nicht auf alles perfekt, nur für die relevanten HTTP Kommandos. Und ja wir können halt nicht garantieren das in jeder Umgebung die Hardware läuft, daher ist das Netzwerk auch primär für die Konfiguration gedacht ist und nicht für den Dauerbetrieb notwendig sein müsste. So oder so, bitte beim Support melden, wenn Sie möchten das wir uns das Problem tiefergehend angucken, aber in dem Fall müssten Sie halt schauen welches Gerät das ist was den SunRiser zum Absturz bringt. Wenn es immer passiert egal mit welchen Geräten kann ja auch ein Hardware defekt da sein, und dann kann man die Geräte tauschen. Alles halt weniger passend für GitHub.

**Comment by findies** [comment]
Den Sunriser hatte ich bereits ausgetauscht, weil das auch meine Vermutung war. der neue machte dieselben Probleme. Deswegen vermutete ich, dass es etwas mit Software zu tun hat. Und wenn nicht hier, wo dann, sollte ich dieses Problem anbringen?
Da hier Software entwickelt wird, hoffte ich, dass es vielleicht mit 'nem  FW-Update oder ähnlichem zu korrigieren wäre .

Was soll denn das für eine Netzwerkkomponente sein, die keinen Dauerbetrieb verträgt? NTP Server ist dann ja auch nicht erreichbar. 
Ganz zu schweigen von zukünftigen Funktionen wie Sonnenaufgang, -untergang an deinen Ort gekoppelt. Aber so etwas scheint es in Zukunft nicht zu geben, scheinbar. Hier scheint sich nix mehr weiter zu entwickeln.

Den Support hatte ich bereits  kontaktiert, die ständige Aussage SD-Karte ersetzten, triffts langsam nicht mehr. Von daher...,  sollte irgendwann eine Komponente kaputtgehen, wird wohl ein Systemwechsel anstehen.

**Comment by Getty** [comment]
Ich hab nicht gesagt das es nicht für den Dauerbetrieb geeignet ist, sondern das es nicht notwendig ist für die meisten User, wenn es halt so eine Komplikation gibt, wie das kollidieren mit anderen Diensten im Netzwerk, wonach es halt aussieht bei Ihrer Beschreibung. Ich würde halt mal jedes Gerät abklemmen um rauszufinden wer das ist, dann hat man schonmal einen Ansatz. Die an den Ort gekoppelten Funktionen würden mit Datenpaketen arbeiten (d.h. kurzfristige Verbindung würde reichen), wir sind nur einfach nicht dazu gekommen hier die nächsten Stufen zu machen, wegen der Sensoren Thematik. Ich werde gern mal mit dem Support von LEDaquaristik reden was hier schief ging, weil normalerweise sollten solche Problem auch dann weitergereicht werden wenn die Basis Lösungen nicht gehen. Es ist halt wirklich in 99% der Fälle nur eine defekte SD Karte (und das Thema z.b. ist für viele Kunden auch sehr wichtig, multiple Datenführung ist aber auf unserer Todo).

Die Frage ist halt wie effektiv dies ist halt im öffentlichen GitHub breitzutreten bevor wir überhaupt wissen was das Problem ist. Daher, wenn Sie das Thema vertiefen wollen können wir dies gern am besten über sunriser@ledaquaristik.de tun.
